from __future__ import annotations

import asyncio
from dataclasses import dataclass


@dataclass(slots=True)
class GenerationConfig:
    model: str = "Qwen/Qwen2.5-Coder-7B-Instruct"
    temperature: float = 0.2
    top_p: float = 0.95
    repetition_penalty: float = 1.05
    max_tokens: int = 128
    stop: tuple[str, ...] = ("<fim_prefix>", "<fim_suffix>", "<fim_middle>", "<|endoftext|>")
    use_speculative: bool = True
    draft_model: str = "Qwen/Qwen2.5-Coder-1.5B-Instruct"


class VLLMClient:
    """Dev wrapper for vLLM OpenAI-compatible streaming.

    Replace `_fake_stream` with real HTTP streaming call to vLLM server.
    """

    async def stream_generate(self, prompt: str, cfg: GenerationConfig):
        del prompt
        async for token in self._fake_stream(cfg):
            if token in cfg.stop:
                break
            yield token

    async def _fake_stream(self, cfg: GenerationConfig):
        base = "\n# generated by vLLM\npass\n"[: cfg.max_tokens]
        step_delay = 0.0025 if cfg.use_speculative else 0.004
        for ch in base:
            await asyncio.sleep(step_delay)
            yield ch
